var people = [
	{name: '@AntonvonRaumer',tz: 'Germany',            color: '#FF8585'},
	{name: '@ciba43',        tz: 'Latvia',             color: '#FE2F77'},
	{name: '@coolsquid_',    tz: 'Norway',             color: '#079DE9'},
	{name: '@Creeper32605',  tz: 'Denmark',            color: '#C8F080'},
	{name: '@Deli731234',    tz: 'USA, Pacific Time',  color: '#A659E2'},
	{name: '@eevblog',       tz: 'Australia, Sydney',  color: '#E63E3F'},
	{name: '@elakdawalla',   tz: 'USA, Pacific Time',  color: '#C49B6D'},
	{name: '@iamSethD',      tz: 'USA, Eastern Time',  color: '#ED2222'},
	{name: '@ImReble548',    tz: 'USA, Mountain Time', color: '#69E79E'},
	{name: '@Jaredlll08',    tz: 'South Africa',       color: '#F86752'},
	{name: '@JesperJacoben', tz: 'Denmark',            color: 'skyblue'},
	{name: '@lastofavari',   tz: 'Belarus',            color: '#05CDC0'},
	{name: '@ljfa2',         tz: 'Germany',            color: '#78FCFF'},
	{name: '@Locercus',      tz: 'Denmark',            color: '#32CD32'},
	{name: '@Lunatrius',     tz: 'Slovenia',           color: '#00CCFF'},
	{name: '@MightyPork',    tz: 'Czech Republic',     color: '#FFAD00'},
	{name: '@Rafmaninoff',   tz: 'Spain',              color: '#00CC00'},
	{name: '@TheBadFame',    tz: 'Mexico',             color: '#329AFF'},
	{name: '@Vangoule273',   tz: 'United Kingdom',     color: '#00FF2C'},
	{name: '@xTordX',        tz: 'Romania',            color: '#AE1AF7'},
];
